const WeatherActionTypes = {
  SET_WEATHER: 'SET_WEATHER',
  SET_CITY: 'SET_CITY',
  FETCH_CURRENT_WEATHER_START: 'FETCH_CURRENT_WEATHER_START',
  FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
  FETCH_CURRENT_WEATHER_FAILURE: 'FETCH_CURRENT_WEATHER_FAILURE',
};

export default WeatherActionTypes;
